### ISSUE TITLE
Upgrade Splash Screen to Android 12 

### ISSUE THREAD

**Issue by rohanbabbar04** [rahulsain/SharedNotes#28]
Currently, the splash screen is implemented with the help of a handler.
But the androidx implementation can be used 

I would like to work on it

**Comment by rahulsain** [comment]
Can you send a reference link or screenshot of that you will try to achieve?

**Comment by rohanbabbar04** [comment]
https://developer.android.com/about/versions/12/splash-screen-migration

**Comment by rohanbabbar04** [comment]
Do assign me @rahulsain

**Comment by rahulsain** [comment]
@rohanbabbar04 you working on this?

**Comment by rohanbabbar04** [comment]
Yes
